[project]
name = "vibrae-shared"
version = "0.1.0"
description = "Shared cross-cutting utilities for Vibrae"
license = { text = "GPL-3.0-or-later" }
authors = [ { name = "Dani Callero" } ]
readme = "../../README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py311"
