creation_rules:
  - path_regex: '^config/env/\.env\.(backend|frontend|runtime)(\.enc)?$'
    key_groups:
      - pgp:
          - FF46BCFF59A65BC21DA916A289FC9A82DD3ECF94  # dani's macbook
    encrypted_regex: '.*'

