version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: vibrae/api:dev
    restart: unless-stopped
    env_file:
      - config/env/.env.runtime.enc # decrypted at deploy time (SOPS)
    networks:
      - vibrae-internal
    volumes:
      - music-data:/app/music:ro
      - app-data:/app/data

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - FRONTEND_PORT=${FRONTEND_PORT:-9081}
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/web/dist:/usr/share/nginx/html:ro
    networks:
      - vibrae-internal
      - vibrae-public

  tailscale:
    image: tailscale/tailscale:latest
    hostname: vibrae
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY:-}
      - TS_EXTRA_ARGS=--accept-dns=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped

networks:
  vibrae-internal:
    internal: true
  vibrae-public: {}

volumes:
  music-data: {}
  app-data: {}
  tailscale-state: {}
