name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff)
        run: |
          ruff check packages/core/src apps/api/src || true

      - name: Secret scan (plaintext env guard)
        run: |
          set -e
          if git ls-files | grep -q '^config/env/.env.backend$'; then
            echo "❌ Plaintext config/env/.env.backend is tracked!" >&2
            echo "Only .env.backend.enc should be committed." >&2
            exit 1
          fi
          if git ls-files | grep -q '^config/env/.env.frontend$'; then
            echo "❌ Plaintext config/env/.env.frontend is tracked!" >&2
            echo "Only .env.frontend.enc should be committed." >&2
            exit 1
          fi
          echo "✓ No tracked plaintext env files"

      - name: Run tests
        run: pytest -q

      - name: Upload coverage placeholder
        if: always()
        run: echo "Add coverage tooling later" 
